"""
PDF Generator for EduGenius
Creates printable worksheets and marking schemes
"""

import streamlit as st
from datetime import datetime

FPDF = None
_FPDF_IMPORT_ERROR = None


def _load_fpdf():
    global FPDF, _FPDF_IMPORT_ERROR
    if FPDF is not None or _FPDF_IMPORT_ERROR is not None:
        return
    try:
        from fpdf import FPDF as _FPDF
        FPDF = _FPDF
    except Exception as e:
        _FPDF_IMPORT_ERROR = e


def create_worksheet_pdf(
    worksheet_text: str,
    subject: str,
    topic: str,
    curriculum: str
) -> bytes:
    """Generate a PDF from worksheet text"""
    
    _load_fpdf()
    if FPDF is None:
        raise RuntimeError(f"FPDF import failed: {_FPDF_IMPORT_ERROR}")

    class WorksheetPDF(FPDF):
        """Custom PDF class for worksheets"""
        
        def header(self):
            self.set_font("Helvetica", "B", 14)
            self.cell(0, 10, "EduGenius Worksheet", align="C", new_x="LMARGIN", new_y="NEXT")
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.ln(5)
        
        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.cell(0, 10, f"Generated by EduGenius | Page {self.page_no()}/{{nb}}", align="C")

    pdf = WorksheetPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"{curriculum} - {subject}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"Topic: {topic}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%B %d, %Y')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    # Content
    pdf.set_font("Helvetica", "", 11)
    
    # Split text into lines and add to PDF
    lines = worksheet_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(4)
        elif line.startswith('---'):
            pdf.ln(4)
            pdf.set_draw_color(255, 107, 53)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(4)
        elif line.startswith('#') or line.startswith('MARKING SCHEME'):
            pdf.set_font("Helvetica", "B", 13)
            pdf.ln(4)
            pdf.cell(0, 8, line.replace('#', '').strip(), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 11)
        elif line.startswith('**') and line.endswith('**'):
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 6, line.replace('**', ''), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 11)
        else:
            # Handle special characters
            line = line.replace('°', ' degrees ')
            line = line.replace('→', ' -> ')
            line = line.replace('×', ' x ')
            
            try:
                pdf.multi_cell(0, 6, line)
            except:
                pdf.multi_cell(0, 6, line.encode('latin-1', 'replace').decode('latin-1'))
    
    return pdf.output()

def generate_download_button(worksheet_text: str, subject: str, topic: str, curriculum: str):
    """Create a download button for PDF export"""
    
    try:
        pdf_bytes = create_worksheet_pdf(worksheet_text, subject, topic, curriculum)
        
        filename = f"{curriculum}_{subject}_{topic.replace(' ', '_')}.pdf"
        
        st.download_button(
            label="📥 Download as PDF",
            data=pdf_bytes,
            file_name=filename,
            mime="application/pdf",
            use_container_width=True
        )
    except Exception as e:
        st.warning(f"PDF generation unavailable: {str(e)}")