"""
PDF Generator for EduGenius
Creates printable worksheets and marking schemes
"""

import streamlit as st
from datetime import datetime
from fpdf import FPDF

def sanitize_text(text):
    """Clean text to remove non-standard characters that crash FPDF"""
    replacements = {
        '–': '-',  # en-dash
        '—': '-',  # em-dash
        '•': '-',  # bullet
        '“': '"',  # smart quote
        '”': '"',  # smart quote
        '‘': "'",  # smart single quote
        '’': "'",  # smart single quote
        '…': '...' # ellipsis
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text

def create_worksheet_pdf(
    worksheet_text: str,
    subject: str,
    topic: str,
    curriculum: str
) -> bytes:
    """Generate a PDF from worksheet text"""

    class WorksheetPDF(FPDF):
        """Custom PDF class for worksheets"""

        def header(self):
            self.set_font("Helvetica", "B", 14)
            self.cell(0, 10, "EduGenius Worksheet", align="C", new_x="LMARGIN", new_y="NEXT")
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.cell(0, 10, f"Generated by EduGenius | Page {self.page_no()}/{{nb}}", align="C")

    pdf = WorksheetPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"{curriculum} - {subject}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"Topic: {topic}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%B %d, %Y')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Content
    pdf.set_font("Helvetica", "", 11)

    # Split text into lines and add to PDF
    lines = worksheet_text.split('\n')
    for line in lines:
        # Sanitize the line first
        line = sanitize_text(line.strip())
        
        if not line:
            pdf.ln(4)
        elif line.startswith('---'):
            pdf.ln(4)
            pdf.set_draw_color(255, 107, 53)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(4)
        elif line.startswith('#') or line.startswith('MARKING SCHEME'):
            pdf.set_font("Helvetica", "B", 13)
            pdf.ln(4)
            pdf.cell(0, 8, line.replace('#', '').strip(), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 11)
        elif line.startswith('**') and line.endswith('**'):
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 6, line.replace('**', ''), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 11)
        else:
            # Handle special characters
            line = line.replace('°', ' degrees ')
            line = line.replace('→', ' -> ')
            line = line.replace('×', ' x ')

            # Force encode/decode to catch any remaining edge cases
            safe_line = line.encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6, safe_line)

    return pdf.output()

def generate_download_button(worksheet_text: str, subject: str, topic: str, curriculum: str):
    """Create a download button for PDF export"""

    try:
        pdf_bytes = create_worksheet_pdf(worksheet_text, subject, topic, curriculum)
        filename = f"{curriculum}_{subject}_{topic.replace(' ', '_')}.pdf"

        st.download_button(
            label="📥 Download as PDF",
            data=pdf_bytes,
            file_name=filename,
            mime="application/pdf",
            use_container_width=True
        )
    except Exception as e:
        st.warning(f"PDF generation unavailable: {str(e)}")
